# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPainter,QPixmap
import time
from threading import Thread


class Ui_Form(object):
    #def __init__(self):
    #    super().__init__()
    def paintEvent(self, event):
        painter = QPainter(self)
        pixmap = QPixmap("./images/bg.jpg")
        painter.drawPixmap(self.rect(), pixmap)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1129, 477)
        Form.setAcceptDrops(False)
        #palette1 = QtGui.QPalette()
        #palette1.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap('images/bg.jpg')))   # 设置背景图片,当背景图片宽度高度小于窗口的宽度高度时，则会加载多个背景图片
        #Form.setPalette(palette1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(530, 210, 51, 31))
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(590, 220, 16, 16))
        self.checkBox.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/bg1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox.setIcon(icon)
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 72, 15))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(50, 120, 111, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        for i in range(6):
            self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 60, 181, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(330, 210, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 210, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(400, 250, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(530, 250, 51, 31))
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(330, 250, 61, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(590, 260, 16, 16))
        self.checkBox_2.setText("")
        self.checkBox_2.setIcon(icon)
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(400, 280, 113, 21))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(530, 290, 51, 31))
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(310, 290, 81, 20))
        self.label_9.setObjectName("label_9")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QtCore.QRect(590, 300, 16, 16))
        self.checkBox_3.setText("")
        self.checkBox_3.setIcon(icon)
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(400, 310, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(530, 320, 51, 31))
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(340, 320, 51, 16))
        self.label_12.setObjectName("label_12")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(590, 330, 16, 16))
        self.checkBox_4.setText("")
        self.checkBox_4.setIcon(icon)
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(400, 340, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(530, 350, 51, 31))
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(340, 350, 51, 16))
        self.label_15.setObjectName("label_15")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setEnabled(True)
        self.checkBox_5.setGeometry(QtCore.QRect(590, 360, 16, 16))
        self.checkBox_5.setText("")
        self.checkBox_5.setIcon(icon)
        self.checkBox_5.setObjectName("checkBox_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(400, 380, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(530, 380, 51, 31))
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(340, 380, 51, 16))
        self.label_18.setObjectName("label_18")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setEnabled(True)
        self.checkBox_6.setGeometry(QtCore.QRect(590, 390, 16, 16))
        self.checkBox_6.setText("")
        self.checkBox_6.setIcon(icon)
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(860, 60, 181, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 118, 23))
        #for value in range(30):
        #    self.progressBar.setProperty("value", value)
        self.progressBar.setObjectName("progressBar")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(30, 270, 72, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(30, 210, 81, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 240, 91, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(30, 350, 72, 15))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(330, 180, 72, 15))
        self.label_23.setObjectName("label_23")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(30, 370, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(420, 180, 72, 15))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(520, 180, 91, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(530, 410, 51, 31))
        self.label_26.setWordWrap(False)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(340, 410, 51, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(400, 410, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setEnabled(True)
        self.checkBox_7.setGeometry(QtCore.QRect(590, 420, 16, 16))
        self.checkBox_7.setText("")
        self.checkBox_7.setIcon(icon)
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(1030, 220, 51, 31))
        self.label_29.setWordWrap(False)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(820, 220, 72, 15))
        self.label_30.setObjectName("label_30")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(900, 220, 113, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setEnabled(True)
        self.checkBox_8.setGeometry(QtCore.QRect(1090, 220, 16, 16))
        self.checkBox_8.setText("")
        self.checkBox_8.setIcon(icon)
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(1030, 260, 51, 31))
        self.label_32.setWordWrap(False)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(820, 260, 72, 15))
        self.label_33.setObjectName("label_33")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(900, 260, 113, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setEnabled(True)
        self.checkBox_9.setGeometry(QtCore.QRect(1090, 270, 16, 16))
        self.checkBox_9.setText("")
        self.checkBox_9.setIcon(icon)
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(1030, 310, 51, 31))
        self.label_35.setWordWrap(False)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(820, 310, 72, 15))
        self.label_36.setObjectName("label_36")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(900, 310, 113, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setEnabled(True)
        self.checkBox_10.setGeometry(QtCore.QRect(1090, 320, 16, 16))
        self.checkBox_10.setText("")
        self.checkBox_10.setIcon(icon)
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(960, 400, 141, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 210, 88, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 250, 88, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 290, 88, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(240, 320, 61, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(720, 220, 88, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(720, 260, 88, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(720, 300, 88, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 350, 61, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 380, 61, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(240, 410, 61, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(670, 160, 151, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setGeometry(QtCore.QRect(200, 210, 16, 19))
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setGeometry(QtCore.QRect(200, 250, 16, 19))
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(Form)
        self.checkBox_13.setGeometry(QtCore.QRect(200, 290, 16, 19))
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(Form)
        self.checkBox_14.setGeometry(QtCore.QRect(200, 320, 16, 19))
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(Form)
        self.checkBox_15.setGeometry(QtCore.QRect(200, 350, 16, 19))
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Form)
        self.checkBox_16.setGeometry(QtCore.QRect(200, 380, 16, 19))
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(Form)
        self.checkBox_17.setGeometry(QtCore.QRect(200, 410, 16, 19))
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(Form)
        self.checkBox_18.setGeometry(QtCore.QRect(690, 220, 16, 19))
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(Form)
        self.checkBox_19.setGeometry(QtCore.QRect(690, 260, 16, 19))
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(Form)
        self.checkBox_20.setGeometry(QtCore.QRect(690, 300, 16, 19))
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setGeometry(QtCore.QRect(190, 180, 41, 20))
        self.label_38.setObjectName("label_38")

        box_l = [i for i in range(2,11)]
        label_l = [5, 8, 11, 14, 17, 26, 29, 32, 35]
        global checkBox_label
        checkBox_label = dict(zip(box_l, label_l)) 
        self.checkBox.toggled['bool'].connect(lambda : self.setLabelText2(0))
        self.checkBox_2.toggled['bool'].connect(lambda : self.setLabelText2(2))
        self.checkBox_3.toggled['bool'].connect(lambda : self.setLabelText2(3))
        self.checkBox_4.toggled['bool'].connect(lambda : self.setLabelText2(4))
        self.checkBox_5.toggled['bool'].connect(lambda : self.setLabelText2(5))
        self.checkBox_6.toggled['bool'].connect(lambda : self.setLabelText2(6))
        self.checkBox_7.toggled['bool'].connect(lambda : self.setLabelText2(7))
        self.checkBox_8.toggled['bool'].connect(lambda : self.setLabelText2(8))
        self.checkBox_9.toggled['bool'].connect(lambda : self.setLabelText2(9))
        self.checkBox_10.toggled['bool'].connect(lambda : self.setLabelText2(10))

        self.pushButton.clicked.connect(self.msg)
        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.close)
        #for i in range(2,11):
        #    print(i)
        #    func = "self.checkBox_" + str(i) + ".toggled['bool'].connect(lambda self: self.setLabelText2(i))"
        #    eval(func)
        #lthread = Thread(target = self.show_progress, args = (101, 1))
        #lthread.start()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def setLabelText2(self, num):
        global checkBox_label
        if num == 0:
            if self.checkBox.isChecked():
                eval("self.label.setText('<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>')")
            else:
                eval("self.label.setText('<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>')")
        else:
            if eval("self.checkBox_" + str(num) + ".isChecked()"):
                #self.label.setText("<html><head/><body><p><span style=\"font-size:14pt; font-weight:600;\">( )</span></p></body></html>")
                eval("self.label_" + str(checkBox_label[num]) +".setText('<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>')")
            else:
                eval("self.label_" + str(checkBox_label[num]) +".setText('<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>')")

    def msg(self):
        #directory1 = QFileDialog.getExistingDirectory(None,
        #            "选取文件夹",
        #            "./")                 #起始路径
        #fileName1, filetype = QFileDialog.getOpenFileName(None,
        #            "选取文件",
        #            "./",
        #            "All Files (*);;Text Files (*.txt)")  #设置文件扩展名过滤,注意用双分号间隔
        #print(fileName1,filetype)

        #files, ok1 = QFileDialog.getOpenFileNames(None,
        #            "多文件选择",
        #            "./",
        #            "All Files (*);;Text Files (*.txt)")
        #print(files,ok1)

        fileName2, ok2 = QFileDialog.getSaveFileName(None,
                    "文件保存",
                    "./",
                    "All Files (*);;Text Files (*.txt)")
        f = open(fileName2, 'w')
        f.close()

    def show_progress(self, num, time_interval):
        for value in range(num):
            time.sleep(1)
            self.progressBar.setProperty("value", value)


    #def setupUi(self, Form):
    #    Form.setObjectName("Form")
    #    Form.resize(1263, 477)
    #    Form.setAcceptDrops(False)
    #    self.lineEdit = QtWidgets.QLineEdit(Form)
    #    self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 21))
    #    self.lineEdit.setText("")
    #    self.lineEdit.setObjectName("lineEdit")
    #    self.label = QtWidgets.QLabel(Form)
    #    self.label.setGeometry(QtCore.QRect(470, 210, 51, 31))
    #    self.label.setWordWrap(False)
    #    self.label.setObjectName("label")
    #    self.label_2 = QtWidgets.QLabel(Form)
    #    self.label_2.setGeometry(QtCore.QRect(520, 210, 51, 31))
    #    self.label_2.setObjectName("label_2")
    #    self.checkBox = QtWidgets.QCheckBox(Form)
    #    self.checkBox.setEnabled(True)
    #    self.checkBox.setGeometry(QtCore.QRect(580, 220, 16, 16))
    #    self.checkBox.setText("")
    #    icon = QtGui.QIcon()
    #    icon.addPixmap(QtGui.QPixmap("images/bg1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    #    self.checkBox.setIcon(icon)
    #    self.checkBox.setObjectName("checkBox")
    #    self.label_3 = QtWidgets.QLabel(Form)
    #    self.label_3.setGeometry(QtCore.QRect(70, 100, 72, 15))
    #    self.label_3.setObjectName("label_3")
    #    self.comboBox = QtWidgets.QComboBox(Form)
    #    self.comboBox.setGeometry(QtCore.QRect(50, 120, 111, 22))
    #    self.comboBox.setEditable(False)
    #    self.comboBox.setObjectName("comboBox")
    #    for i in range(6):
    #        self.comboBox.addItem("") #    self.pushButton = QtWidgets.QPushButton(Form)
       #    self.pushButton.setGeometry(QtCore.QRect(360, 60, 181, 23))
    #    palette = QtGui.QPalette()
    #    brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
    #    brush.setStyle(QtCore.Qt.SolidPattern)
    #    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
    #    brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
    #    brush.setStyle(QtCore.Qt.SolidPattern)
    #    palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
    #    brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
    #    brush.setStyle(QtCore.Qt.SolidPattern)
    #    palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
    #    self.pushButton.setPalette(palette)
    #    self.pushButton.setObjectName("pushButton")
    #    self.label_4 = QtWidgets.QLabel(Form)
    #    self.label_4.setGeometry(QtCore.QRect(260, 210, 72, 15))
    #    self.label_4.setObjectName("label_4")
    #    self.lineEdit_2 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_2.setGeometry(QtCore.QRect(340, 210, 113, 21))
    #    self.lineEdit_2.setObjectName("lineEdit_2")
    #    self.lineEdit_3 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_3.setGeometry(QtCore.QRect(340, 250, 113, 21))
    #    self.lineEdit_3.setObjectName("lineEdit_3")
    #    self.label_5 = QtWidgets.QLabel(Form)
    #    self.label_5.setGeometry(QtCore.QRect(470, 250, 51, 31))
    #    self.label_5.setWordWrap(False)
    #    self.label_5.setObjectName("label_5")
    #    self.label_6 = QtWidgets.QLabel(Form)
    #    self.label_6.setGeometry(QtCore.QRect(260, 250, 72, 15))
    #    self.label_6.setObjectName("label_6")
    #    self.label_7 = QtWidgets.QLabel(Form)
    #    self.label_7.setGeometry(QtCore.QRect(520, 250, 51, 31))
    #    self.label_7.setObjectName("label_7")
    #    self.checkBox_2 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_2.setEnabled(True)
    #    self.checkBox_2.setGeometry(QtCore.QRect(580, 260, 16, 16))
    #    self.checkBox_2.setText("")
    #    self.checkBox_2.setIcon(icon)
    #    self.checkBox_2.setObjectName("checkBox_2")
    #    self.lineEdit_4 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_4.setGeometry(QtCore.QRect(340, 290, 113, 21))
    #    self.lineEdit_4.setText("")
    #    self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
    #    self.lineEdit_4.setReadOnly(True)
    #    self.lineEdit_4.setObjectName("lineEdit_4")
    #    self.label_8 = QtWidgets.QLabel(Form)
    #    self.label_8.setGeometry(QtCore.QRect(470, 290, 51, 31))
    #    self.label_8.setWordWrap(False)
    #    self.label_8.setObjectName("label_8")
    #    self.label_9 = QtWidgets.QLabel(Form)
    #    self.label_9.setGeometry(QtCore.QRect(251, 290, 81, 20))
    #    self.label_9.setObjectName("label_9")
    #    self.label_10 = QtWidgets.QLabel(Form)
    #    self.label_10.setGeometry(QtCore.QRect(520, 290, 51, 31))
    #    self.label_10.setObjectName("label_10")
    #    self.checkBox_3 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_3.setEnabled(True)
    #    self.checkBox_3.setGeometry(QtCore.QRect(580, 300, 16, 16))
    #    self.checkBox_3.setText("")
    #    self.checkBox_3.setIcon(icon)
    #    self.checkBox_3.setObjectName("checkBox_3")
    #    self.lineEdit_5 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_5.setGeometry(QtCore.QRect(340, 320, 113, 21))
    #    self.lineEdit_5.setObjectName("lineEdit_5")
    #    self.label_11 = QtWidgets.QLabel(Form)
    #    self.label_11.setGeometry(QtCore.QRect(470, 320, 51, 31))
    #    self.label_11.setWordWrap(False)
    #    self.label_11.setObjectName("label_11")
    #    self.label_12 = QtWidgets.QLabel(Form)
    #    self.label_12.setGeometry(QtCore.QRect(260, 320, 72, 15))
    #    self.label_12.setObjectName("label_12")
    #    self.label_13 = QtWidgets.QLabel(Form)
    #    self.label_13.setGeometry(QtCore.QRect(520, 320, 51, 31))
    #    self.label_13.setObjectName("label_13")
    #    self.checkBox_4 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_4.setEnabled(True)
    #    self.checkBox_4.setGeometry(QtCore.QRect(580, 330, 16, 16))
    #    self.checkBox_4.setText("")
    #    self.checkBox_4.setIcon(icon)
    #    self.checkBox_4.setObjectName("checkBox_4")
    #    self.lineEdit_6 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_6.setGeometry(QtCore.QRect(340, 350, 113, 21))
    #    self.lineEdit_6.setObjectName("lineEdit_6")
    #    self.label_14 = QtWidgets.QLabel(Form)
    #    self.label_14.setGeometry(QtCore.QRect(470, 350, 51, 31))
    #    self.label_14.setWordWrap(False)
    #    self.label_14.setObjectName("label_14")
    #    self.label_15 = QtWidgets.QLabel(Form)
    #    self.label_15.setGeometry(QtCore.QRect(260, 350, 72, 15))
    #    self.label_15.setObjectName("label_15")
    #    self.label_16 = QtWidgets.QLabel(Form)
    #    self.label_16.setGeometry(QtCore.QRect(520, 350, 51, 31))
    #    self.label_16.setObjectName("label_16")
    #    self.checkBox_5 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_5.setEnabled(True)
    #    self.checkBox_5.setGeometry(QtCore.QRect(580, 360, 16, 16))
    #    self.checkBox_5.setText("")
    #    self.checkBox_5.setIcon(icon)
    #    self.checkBox_5.setObjectName("checkBox_5")
    #    self.lineEdit_7 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_7.setGeometry(QtCore.QRect(340, 380, 113, 21))
    #    self.lineEdit_7.setObjectName("lineEdit_7")
    #    self.label_17 = QtWidgets.QLabel(Form)
    #    self.label_17.setGeometry(QtCore.QRect(470, 380, 51, 31))
    #    self.label_17.setWordWrap(False)
    #    self.label_17.setObjectName("label_17")
    #    self.label_18 = QtWidgets.QLabel(Form)
    #    self.label_18.setGeometry(QtCore.QRect(260, 380, 72, 15))
    #    self.label_18.setObjectName("label_18")
    #    self.label_19 = QtWidgets.QLabel(Form)
    #    self.label_19.setGeometry(QtCore.QRect(520, 380, 51, 31))
    #    self.label_19.setObjectName("label_19")
    #    self.checkBox_6 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_6.setEnabled(True)
    #    self.checkBox_6.setGeometry(QtCore.QRect(580, 390, 16, 16))
    #    self.checkBox_6.setText("")
    #    self.checkBox_6.setIcon(icon)
    #    self.checkBox_6.setObjectName("checkBox_6")
    #    self.pushButton_2 = QtWidgets.QPushButton(Form)
    #    self.pushButton_2.setGeometry(QtCore.QRect(860, 70, 181, 23))
    #    self.pushButton_2.setObjectName("pushButton_2")
    #    self.progressBar = QtWidgets.QProgressBar(Form)
    #    self.progressBar.setGeometry(QtCore.QRect(30, 300, 118, 23))
    #    self.progressBar.setProperty("value", 30)
    #    self.progressBar.setObjectName("progressBar")
    #    self.label_20 = QtWidgets.QLabel(Form)
    #    self.label_20.setGeometry(QtCore.QRect(30, 270, 72, 15))
    #    self.label_20.setObjectName("label_20")
    #    self.label_21 = QtWidgets.QLabel(Form)
    #    self.label_21.setGeometry(QtCore.QRect(30, 210, 81, 16))
    #    self.label_21.setObjectName("label_21")
    #    self.lineEdit_8 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_8.setGeometry(QtCore.QRect(30, 240, 91, 21))
    #    self.lineEdit_8.setObjectName("lineEdit_8")
    #    self.label_22 = QtWidgets.QLabel(Form)
    #    self.label_22.setGeometry(QtCore.QRect(30, 350, 72, 15))
    #    self.label_22.setObjectName("label_22")
    #    self.label_23 = QtWidgets.QLabel(Form)
    #    self.label_23.setGeometry(QtCore.QRect(270, 170, 72, 15))
    #    self.label_23.setObjectName("label_23")
    #    self.timeEdit = QtWidgets.QTimeEdit(Form)
    #    self.timeEdit.setGeometry(QtCore.QRect(30, 370, 118, 22))
    #    self.timeEdit.setObjectName("timeEdit")
    #    self.label_24 = QtWidgets.QLabel(Form)
    #    self.label_24.setGeometry(QtCore.QRect(360, 170, 72, 15))
    #    self.label_24.setObjectName("label_24")
    #    self.label_25 = QtWidgets.QLabel(Form)
    #    self.label_25.setGeometry(QtCore.QRect(460, 170, 111, 20))
    #    self.label_25.setObjectName("label_25")
    #    self.label_26 = QtWidgets.QLabel(Form)
    #    self.label_26.setGeometry(QtCore.QRect(470, 410, 51, 31))
    #    self.label_26.setWordWrap(False)
    #    self.label_26.setObjectName("label_26")
    #    self.label_27 = QtWidgets.QLabel(Form)
    #    self.label_27.setGeometry(QtCore.QRect(260, 410, 72, 15))
    #    self.label_27.setObjectName("label_27")
    #    self.lineEdit_9 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_9.setGeometry(QtCore.QRect(340, 410, 113, 21))
    #    self.lineEdit_9.setObjectName("lineEdit_9")
    #    self.checkBox_7 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_7.setEnabled(True)
    #    self.checkBox_7.setGeometry(QtCore.QRect(580, 420, 16, 16))
    #    self.checkBox_7.setText("")
    #    self.checkBox_7.setIcon(icon)
    #    self.checkBox_7.setObjectName("checkBox_7")
    #    self.label_28 = QtWidgets.QLabel(Form)
    #    self.label_28.setGeometry(QtCore.QRect(520, 410, 51, 31))
    #    self.label_28.setObjectName("label_28")
    #    self.label_29 = QtWidgets.QLabel(Form)
    #    self.label_29.setGeometry(QtCore.QRect(1030, 220, 51, 31))
    #    self.label_29.setWordWrap(False)
    #    self.label_29.setObjectName("label_29")
    #    self.label_30 = QtWidgets.QLabel(Form)
    #    self.label_30.setGeometry(QtCore.QRect(820, 220, 72, 15))
    #    self.label_30.setObjectName("label_30")
    #    self.lineEdit_10 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_10.setGeometry(QtCore.QRect(900, 220, 113, 21))
    #    self.lineEdit_10.setObjectName("lineEdit_10")
    #    self.checkBox_8 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_8.setEnabled(True)
    #    self.checkBox_8.setGeometry(QtCore.QRect(1140, 230, 16, 16))
    #    self.checkBox_8.setText("")
    #    self.checkBox_8.setIcon(icon)
    #    self.checkBox_8.setObjectName("checkBox_8")
    #    self.label_31 = QtWidgets.QLabel(Form)
    #    self.label_31.setGeometry(QtCore.QRect(1080, 220, 51, 31))
    #    self.label_31.setObjectName("label_31")
    #    self.label_32 = QtWidgets.QLabel(Form)
    #    self.label_32.setGeometry(QtCore.QRect(1030, 260, 51, 31))
    #    self.label_32.setWordWrap(False)
    #    self.label_32.setObjectName("label_32")
    #    self.label_33 = QtWidgets.QLabel(Form)
    #    self.label_33.setGeometry(QtCore.QRect(820, 260, 72, 15))
    #    self.label_33.setObjectName("label_33")
    #    self.lineEdit_11 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_11.setGeometry(QtCore.QRect(900, 260, 113, 21))
    #    self.lineEdit_11.setObjectName("lineEdit_11")
    #    self.checkBox_9 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_9.setEnabled(True)
    #    self.checkBox_9.setGeometry(QtCore.QRect(1140, 270, 16, 16))
    #    self.checkBox_9.setText("")
    #    self.checkBox_9.setIcon(icon)
    #    self.checkBox_9.setObjectName("checkBox_9")
    #    self.label_34 = QtWidgets.QLabel(Form)
    #    self.label_34.setGeometry(QtCore.QRect(1080, 260, 51, 31))
    #    self.label_34.setObjectName("label_34")
    #    self.label_35 = QtWidgets.QLabel(Form)
    #    self.label_35.setGeometry(QtCore.QRect(1030, 310, 51, 31))
    #    self.label_35.setWordWrap(False)
    #    self.label_35.setObjectName("label_35")
    #    self.label_36 = QtWidgets.QLabel(Form)
    #    self.label_36.setGeometry(QtCore.QRect(820, 310, 72, 15))
    #    self.label_36.setObjectName("label_36")
    #    self.lineEdit_12 = QtWidgets.QLineEdit(Form)
    #    self.lineEdit_12.setGeometry(QtCore.QRect(900, 310, 113, 21))
    #    self.lineEdit_12.setObjectName("lineEdit_12")
    #    self.checkBox_10 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_10.setEnabled(True)
    #    self.checkBox_10.setGeometry(QtCore.QRect(1140, 320, 16, 16))
    #    self.checkBox_10.setText("")
    #    self.checkBox_10.setIcon(icon)
    #    self.checkBox_10.setObjectName("checkBox_10")
    #    self.label_37 = QtWidgets.QLabel(Form)
    #    self.label_37.setGeometry(QtCore.QRect(1080, 310, 51, 31))
    #    self.label_37.setObjectName("label_37")
    #    self.pushButton_3 = QtWidgets.QPushButton(Form)
    #    self.pushButton_3.setGeometry(QtCore.QRect(1100, 420, 141, 51))
    #    self.pushButton_3.setObjectName("pushButton_3")
    #    self.pushButton_4 = QtWidgets.QPushButton(Form)
    #    self.pushButton_4.setGeometry(QtCore.QRect(630, 220, 88, 23))
    #    self.pushButton_4.setObjectName("pushButton_4")
    #    self.pushButton_5 = QtWidgets.QPushButton(Form)
    #    self.pushButton_5.setGeometry(QtCore.QRect(630, 260, 88, 23))
    #    self.pushButton_5.setObjectName("pushButton_5")
    #    self.pushButton_6 = QtWidgets.QPushButton(Form)
    #    self.pushButton_6.setGeometry(QtCore.QRect(630, 300, 88, 23))
    #    self.pushButton_6.setObjectName("pushButton_6")
    #    self.pushButton_7 = QtWidgets.QPushButton(Form)
    #    self.pushButton_7.setGeometry(QtCore.QRect(640, 330, 61, 23))
    #    self.pushButton_7.setObjectName("pushButton_7")
    #    self.pushButton_8 = QtWidgets.QPushButton(Form)
    #    self.pushButton_8.setGeometry(QtCore.QRect(1170, 220, 88, 23))
    #    self.pushButton_8.setObjectName("pushButton_8")
    #    self.pushButton_9 = QtWidgets.QPushButton(Form)
    #    self.pushButton_9.setGeometry(QtCore.QRect(1170, 270, 88, 23))
    #    self.pushButton_9.setObjectName("pushButton_9")
    #    self.pushButton_10 = QtWidgets.QPushButton(Form)
    #    self.pushButton_10.setGeometry(QtCore.QRect(1170, 310, 88, 23))
    #    self.pushButton_10.setObjectName("pushButton_10")
    #    self.pushButton_11 = QtWidgets.QPushButton(Form)
    #    self.pushButton_11.setGeometry(QtCore.QRect(640, 360, 61, 23))
    #    self.pushButton_11.setObjectName("pushButton_11")
    #    self.pushButton_12 = QtWidgets.QPushButton(Form)
    #    self.pushButton_12.setGeometry(QtCore.QRect(640, 390, 61, 23))
    #    self.pushButton_12.setObjectName("pushButton_12")
    #    self.pushButton_13 = QtWidgets.QPushButton(Form)
    #    self.pushButton_13.setGeometry(QtCore.QRect(640, 420, 61, 23))
    #    self.pushButton_13.setObjectName("pushButton_13")
    #    self.pushButton_14 = QtWidgets.QPushButton(Form)
    #    self.pushButton_14.setGeometry(QtCore.QRect(670, 160, 151, 23))
    #    self.pushButton_14.setObjectName("pushButton_14")
    #    self.checkBox_11 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_11.setGeometry(QtCore.QRect(230, 210, 16, 19))
    #    self.checkBox_11.setText("")
    #    self.checkBox_11.setObjectName("checkBox_11")
    #    self.checkBox_12 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_12.setGeometry(QtCore.QRect(230, 250, 16, 19))
    #    self.checkBox_12.setText("")
    #    self.checkBox_12.setObjectName("checkBox_12")
    #    self.checkBox_13 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_13.setGeometry(QtCore.QRect(230, 290, 16, 19))
    #    self.checkBox_13.setText("")
    #    self.checkBox_13.setObjectName("checkBox_13")
    #    self.checkBox_14 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_14.setGeometry(QtCore.QRect(230, 320, 16, 19))
    #    self.checkBox_14.setText("")
    #    self.checkBox_14.setObjectName("checkBox_14")
    #    self.checkBox_15 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_15.setGeometry(QtCore.QRect(230, 350, 16, 19))
    #    self.checkBox_15.setText("")
    #    self.checkBox_15.setObjectName("checkBox_15")
    #    self.checkBox_16 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_16.setGeometry(QtCore.QRect(230, 380, 16, 19))
    #    self.checkBox_16.setText("")
    #    self.checkBox_16.setObjectName("checkBox_16")
    #    self.checkBox_17 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_17.setGeometry(QtCore.QRect(230, 410, 16, 19))
    #    self.checkBox_17.setText("")
    #    self.checkBox_17.setObjectName("checkBox_17")
    #    self.checkBox_18 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_18.setGeometry(QtCore.QRect(790, 220, 16, 19))
    #    self.checkBox_18.setText("")
    #    self.checkBox_18.setObjectName("checkBox_18")
    #    self.checkBox_19 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_19.setGeometry(QtCore.QRect(790, 260, 16, 19))
    #    self.checkBox_19.setText("")
    #    self.checkBox_19.setObjectName("checkBox_19")
    #    self.checkBox_20 = QtWidgets.QCheckBox(Form)
    #    self.checkBox_20.setGeometry(QtCore.QRect(790, 310, 16, 19))
    #    self.checkBox_20.setText("")
    #    self.checkBox_20.setObjectName("checkBox_20")
    #    self.label_38 = QtWidgets.QLabel(Form)
    #    self.label_38.setGeometry(QtCore.QRect(221, 170, 41, 20))
    #    self.label_38.setObjectName("label_38")

    #    self.retranslateUi(Form)
    #    self.checkBox.toggled['bool'].connect(self.label_2.clear)
    #    self.checkBox.toggled['bool'].connect(self.setLabelText2)
    #    QtCore.QMetaObject.connectSlotsByName(Form)

    #def setLabelText2(self, label):
    #    if self.checkBox.isChecked():
    #        #self.label.setText("<html><head/><body><p><span style=\"font-size:14pt; font-weight:600;\">( )</span></p></body></html>")
    #        self.label.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>")
    #    else:
    #        self.label.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测试界面"))
        self.lineEdit.setPlaceholderText(_translate("Form", "   产品编号"))
        #self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        #self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        #self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "产品类型"))
        #pro_key = [i for i in range(6)]
        #pro_value = [chr(i) for i in range(65,70)]
        #pro_dict = dict(zip(pro_key, pro_value))
        product_dict = {i:chr(65 + i) for i in range(6)}
        for i in sorted(product_dict.keys()):
            self.comboBox.setItemText(i, _translate("Form", product_dict[i]))
        #self.comboBox.setItemText(0, _translate("Form", "A"))
        #self.comboBox.setItemText(1, _translate("Form", "B"))
        #self.comboBox.setItemText(2, _translate("Form", "C"))
        #self.comboBox.setItemText(3, _translate("Form", "D"))
        #self.comboBox.setItemText(4, _translate("Form", "E"))
        #self.comboBox.setItemText(5, _translate("Form", "F"))
        self.pushButton.setText(_translate("Form", "导入已测试数据"))
        self.label_4.setText(_translate("Form", "CPU性能"))
        self.label_5.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        #self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "内存性能"))
        #self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_8.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_9.setText(_translate("Form", "磁盘读写性能"))
        #self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_11.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_12.setText(_translate("Form", "随机读"))
        #self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_14.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_15.setText(_translate("Form", "随机写"))
        #self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_17.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_18.setText(_translate("Form", "顺序读"))
        #self.label_19.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "导出测试报告"))
        self.label_20.setText(_translate("Form", "测试进度"))
        self.label_21.setText(_translate("Form", "当前测试项"))
        self.label_22.setText(_translate("Form", "耗时"))
        self.label_23.setText(_translate("Form", "测试项"))
        self.label_24.setText(_translate("Form", "性能数据"))
        self.label_25.setText(_translate("Form", "通过/未通过"))
        #self.label_26.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_26.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_27.setText(_translate("Form", "顺序写"))
        #self.label_28.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_29.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_29.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_30.setText(_translate("Form", "网络性能"))
        #self.label_31.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_32.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_32.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_33.setText(_translate("Form", "其他项"))
        #self.label_34.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        #self.label_35.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#000000;\">(</span><span style=\" font-size:14pt; font-weight:600; color:#55aa00;\">✔</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">)</span></p></body></html>"))
        self.label_35.setText("<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(</span><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">✖</span><span style=\" font-size:14pt; font-weight:600;\">)</span></p></body></html>")
        self.label_36.setText(_translate("Form", "其他项"))
        #self.label_37.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">( )</span></p></body></html>"))
        for i in range(3,14):
            if i == 3:
                eval("self.pushButton_" + str(i) + ".setText(_translate(\"Form\", \"退出系统\"))")
            else:
                eval("self.pushButton_" + str(i) + ".setText(_translate(\"Form\", \"开始测试\"))")
                #self.pushButton_i.setText(_translate("Form", "开始测试"))
        #self.pushButton_3.setText(_translate("Form", "退出系统"))
        #self.pushButton_4.setText(_translate("Form", "开始测试"))
        #self.pushButton_5.setText(_translate("Form", "开始测试"))
        #self.pushButton_6.setText(_translate("Form", "开始测试"))
        #self.pushButton_7.setText(_translate("Form", "开始测试"))
        #self.pushButton_8.setText(_translate("Form", "开始测试"))
        #self.pushButton_9.setText(_translate("Form", "开始测试"))
        #self.pushButton_10.setText(_translate("Form", "开始测试"))
        #self.pushButton_11.setText(_translate("Form", "开始测试"))
        #self.pushButton_12.setText(_translate("Form", "开始测试"))
        #self.pushButton_13.setText(_translate("Form", "开始测试"))
        self.pushButton_14.setText(_translate("Form", "批量测试"))
        self.label_38.setText(_translate("Form", "选择"))

def time_consu(func):
    def wrapper(*args, **kwargs):
        time=time.now()
        return func(*args, **kwargs)
    return wrapper

def run():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    run()